Repository Azure/Commercial-Marketplace-SaaS-Accelerator, pull requests merged in 2021-09, with the labels that each got.

#124 Added Multi-Tenant to Admin page.
  src/SaaS.SDK.PublisherSolution/Startup.cs
Labels: enhancement

#122 Adding Admin App Changes
  src/SaaS.SDK.PublisherSolution/Views/Home/Index.cshtml
  src/SaaS.SDK.PublisherSolution/Views/Home/SubscriptionLogDetail.cshtml
  src/SaaS.SDK.PublisherSolution/Views/Offers/Index.cshtml
  src/SaaS.SDK.PublisherSolution/Views/Offers/OfferDetails.cshtml
  src/SaaS.SDK.PublisherSolution/Views/Plans/PlanDetails.cshtml
  src/SaaS.SDK.PublisherSolution/Views/Shared/_Layout.cshtml
  src/SaaS.SDK.PublisherSolution/wwwroot/css/Custom.css
  src/SaaS.SDK.PublisherSolution/wwwroot/css/jquery-ui/jquery-ui.css
  src/SaaS.SDK.PublisherSolution/wwwroot/css/site.css
  src/SaaS.SDK.PublisherSolution/wwwroot/lib/bootstrap/4.4.1/css/bootstrap.min.css
  src/SaaS.SDK.PublisherSolution/wwwroot/lib/bootstrap/4.4.1/css/offcanvas.css
Labels: enhancement

#126 App registration
  deployment/Templates/AMPSaaSDatabase/AMPSaaSDB.bacpac
  deployment/Templates/Deploy.ps1
  docs/Advanced-Instructions.md
  docs/Installation-Instructions.md
  docs/images/portal-cloudshell.png
Labels: documentation, enhancement

#129 Landing Page Changes
  src/SaaS.SDK.CustomerProvisioning/wwwroot/css/Custom.css
Labels: enhancement

#132 fix for AAD delay, plus stop script if it fails
  deployment/Templates/Deploy.ps1
Labels: bug
