Repository Azure/Commercial-Marketplace-SaaS-Accelerator, pull requests merged in 2022-02, with the labels that each got.

#184 Add Back button to Application Config Details page
  src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/ApplicationConfigDetails.cshtml
Labels: enhancement

#190 Code cleanup and fix for plan fields.
  src/SaaS.SDK.Client.DataAccess/Context/SaasKitContext.cs
  src/SaaS.SDK.Client.DataAccess/Contracts/IApplicationLogRepository.cs
  src/SaaS.SDK.Client.DataAccess/Contracts/IEventsRepository.cs
  src/SaaS.SDK.Client.DataAccess/Entities/ApplicationConfiguration.cs
  src/SaaS.SDK.Client.DataAccess/Entities/ApplicationLog.cs
  src/SaaS.SDK.Client.DataAccess/Entities/DatabaseVersionHistory.cs
  src/SaaS.SDK.Client.DataAccess/Entities/EmailTemplate.cs
  src/SaaS.SDK.Client.DataAccess/Entities/Events.cs
  src/SaaS.SDK.Client.DataAccess/Entities/KnownUsers.cs
  src/SaaS.SDK.Client.DataAccess/Entities/MeteredAuditLogs.cs
  src/SaaS.SDK.Client.DataAccess/Entities/MeteredDimensions.cs
  src/SaaS.SDK.Client.DataAccess/Entities/OfferAttributes.cs
  src/SaaS.SDK.Client.DataAccess/Entities/Offers.cs
  src/SaaS.SDK.Client.DataAccess/Entities/PlanAttributeMapping.cs
  src/SaaS.SDK.Client.DataAccess/Entities/PlanAttributeOutput.cs
  src/SaaS.SDK.Client.DataAccess/Entities/PlanEventsMapping.cs
  src/SaaS.SDK.Client.DataAccess/Entities/PlanEventsOutPut.cs
  src/SaaS.SDK.Client.DataAccess/Entities/Roles.cs
  src/SaaS.SDK.Client.DataAccess/Entities/SubscriptionAttributeValues.cs
  src/SaaS.SDK.Client.DataAccess/Entities/SubscriptionAuditLogs.cs
  src/SaaS.SDK.Client.DataAccess/Entities/SubscriptionEmailOutput.cs
  src/SaaS.SDK.Client.DataAccess/Entities/SubscriptionParametersOutput.cs
  src/SaaS.SDK.Client.DataAccess/Entities/ValueTypes.cs
  src/SaaS.SDK.Client.DataAccess/Entities/WebJobSubscriptionStatus.cs
  src/SaaS.SDK.Client.DataAccess/Services/EventsRepository.cs
  src/SaaS.SDK.Client.DataAccess/Services/OfferAttributesRepository.cs
  src/SaaS.SDK.CustomerProvisioning/WebHook/WebhookHandler.cs
  src/SaaS.SDK.PublisherSolution/Controllers/ApplicationConfigController.cs
  src/SaaS.SDK.Services/Helpers/EmailHelper.cs
  src/SaaS.SDK.Services/Models/AzureWebhookPayLoad.cs
  src/SaaS.SDK.Services/Models/ErrorViewModel.cs
  src/SaaS.SDK.Services/Models/MeteringDimension.cs
  src/SaaS.SDK.Services/Models/MeteringErrorResult.cs
  src/SaaS.SDK.Services/Models/MeteringedQuantityIncluded.cs
  src/SaaS.SDK.Services/Models/PlanDetailResult.cs
  src/SaaS.SDK.Services/Services/ApplicationConfigurationService.cs
  src/SaaS.SDK.Services/Services/SubscriptionService.cs
  src/SaaS.SDK.Services/WebHook/WebhookProcessor.cs
Labels: bug

#192 Fix Subscriptions table for publisher portal
  src/SaaS.SDK.PublisherSolution/Views/Home/Subscriptions.cshtml
  src/SaaS.SDK.Services/Services/SMTPEmailService.cs
Labels: bug

#194 add saas diagram
  README.md
  docs/images/saasoverview.png
Labels: documentation
