Repository Azure/Commercial-Marketplace-SaaS-Accelerator, pull requests merged in 2022-03, with the labels that each got.

#201 Replace the Activate to Subscribe on Portal if SA is configured as Delay Activation #196
  deployment/Database/README.md
  src/SaaS.SDK.CustomerProvisioning/Controllers/HomeController.cs
  src/SaaS.SDK.CustomerProvisioning/Views/Home/Subscriptions.cshtml
  src/SaaS.SDK.CustomerProvisioning/Views/Home/_LandingPage.cshtml
  src/SaaS.SDK.PublisherSolution/Controllers/HomeController.cs
  src/SaaS.SDK.Services/Models/SubscriptionResultExtension.cs
  src/SaaS.SDK.Services/Models/SubscriptionViewModel.cs
Labels: enhancement

#182 Fix Webhook Controller (fix #179)
  src/SaaS.SDK.Client.DataAccess/Services/ApplicationLogRepository.cs
  src/SaaS.SDK.CustomerProvisioning/Controllers/WebHook/AzureWebhookController.cs
Labels: bug, enhancement

#207 Fix offers table, Add Marketplace Subscription ID to Admin portal, Re…
  src/SaaS.SDK.CustomerProvisioning/wwwroot/contoso-sales.png
  src/SaaS.SDK.CustomerProvisioning/wwwroot/favicon.ico
  src/SaaS.SDK.PublisherSolution/Views/Home/Subscriptions.cshtml
  src/SaaS.SDK.PublisherSolution/Views/Offers/Index.cshtml
  src/SaaS.SDK.PublisherSolution/wwwroot/contoso-sales.png
  src/SaaS.SDK.PublisherSolution/wwwroot/favicon.ico
Labels: bug, enhancement

#208 Unsubscribe action for Landing Page. (#123)
  deployment/Database/README.md
  src/SaaS.SDK.CustomerProvisioning/Views/Home/Subscriptions.cshtml
Labels: enhancement

#215 Remove extra scrollbar and move settings link to the top
  src/SaaS.SDK.PublisherSolution/Views/Shared/_Layout.cshtml
  src/SaaS.SDK.PublisherSolution/wwwroot/css/custom.css
Labels: bug

#222 Fix color for hover over 'subscribe' button on lading page
  src/SaaS.SDK.CustomerProvisioning/wwwroot/css/Custom.css
Labels: enhancement

#221 Allow Admin to change logos (#203)
  deployment/Database/AMP-DB-5.0.sql
  deployment/Database/AMPSaaSDB.bacpac
  deployment/Templates/Deploy.ps1
  src/SaaS.SDK.Client.DataAccess/Contracts/IApplicationConfigRepository.cs
  src/SaaS.SDK.Client.DataAccess/Services/ApplicationConfigRepository.cs
  src/SaaS.SDK.CustomerProvisioning/Controllers/HomeController.cs
  src/SaaS.SDK.PublisherSolution/Controllers/ApplicationConfigController.cs
  src/SaaS.SDK.PublisherSolution/Controllers/HomeController.cs
  src/SaaS.SDK.PublisherSolution/Startup.cs
  src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/Index.cshtml
  src/SaaS.SDK.Services/Services/ApplicationConfigurationService.cs
Labels: enhancement
