Repository Azure/Commercial-Marketplace-SaaS-Accelerator, pull requests merged in 2022-05, with the labels that each got.

#238 Added filter options on the Subscriptions page #204
  src/SaaS.SDK.PublisherSolution/Views/Home/Subscriptions.cshtml
  src/SaaS.SDK.PublisherSolution/wwwroot/css/custom.css
Labels: enhancement

#231 Add Admin page for admin-user managements #143
  src/SaaS.SDK.Client.DataAccess/Context/SaasKitContext.cs
  src/SaaS.SDK.Client.DataAccess/Contracts/IKnownUsersRepository.cs
  src/SaaS.SDK.Client.DataAccess/Services/KnownUsersRepository.cs
  src/SaaS.SDK.PublisherSolution/Controllers/KnownUsersController.cs
  src/SaaS.SDK.PublisherSolution/Views/Home/Index.cshtml
  src/SaaS.SDK.PublisherSolution/Views/KnownUsers/Index.cshtml
  src/SaaS.SDK.PublisherSolution/Views/Shared/_Layout.cshtml
  src/SaaS.SDK.PublisherSolution/wwwroot/lib/bootstrap/4.4.1/css/offcanvas.css
Labels: enhancement

#248 Add check for authenticated user for users page
  src/SaaS.SDK.PublisherSolution/Controllers/KnownUsersController.cs
Labels: bug

#250 Main README restructuring
  README.md
  docs/Advanced-Instructions.md
Labels: documentation
